🤚hi I,m Rohit Chauhan- 
- 👀 I’m interested in python coading and aslo in machine learning ...
- 🌱 I’m currently learning in Qunatum University(4th year)...
- 💞️ I’m looking to collaborate on  startup, MNC...
- 📫 How to reach me- rohitchauhan@745996gmail.com...

<!---
Rohit17chauhan/Rohit17chauhan is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
